package main

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"go.idp.xyz/idp-parcel/internal/parcelpricing/adapters/pricecardtemplate"
)

// 入库模板与生成器输出逐字节相等；不等就是有人手改了模板文件，或改了列定义却没重新生成。
func TestCommittedTemplateMatchesTheGenerator(t *testing.T) {
	committed, err := os.ReadFile(filepath.Join("..", "..", committedPath))
	if err != nil {
		t.Fatalf("读不到入库模板：%v；在仓库根执行 go run ./cmd/parcel-pricing-template 生成", err)
	}
	var generated bytes.Buffer
	if err := pricecardtemplate.WriteTemplate(&generated); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(committed, generated.Bytes()) {
		t.Fatal("入库模板与生成器输出不同；在仓库根执行 go run ./cmd/parcel-pricing-template 重新生成")
	}
}
