package domain

import "errors"

var (
	ErrInvalidDecimal                     = errors.New("parcel pricing: invalid decimal")
	ErrDecimalPrecisionExceeded           = errors.New("parcel pricing: decimal precision exceeded")
	ErrInvalidCurrency                    = errors.New("parcel pricing: invalid currency")
	ErrInvalidChargeCode                  = errors.New("parcel pricing: invalid charge code")
	ErrInvalidMoney                       = errors.New("parcel pricing: invalid money")
	ErrCurrencyMismatch                   = errors.New("parcel pricing: currency mismatch")
	ErrInvalidWeight                      = errors.New("parcel pricing: invalid weight")
	ErrInvalidLength                      = errors.New("parcel pricing: invalid length")
	ErrInvalidLengthUnit                  = errors.New("parcel pricing: invalid length unit")
	ErrLengthUnitMismatch                 = errors.New("parcel pricing: length unit mismatch")
	ErrInvalidDimensions                  = errors.New("parcel pricing: invalid dimensions")
	ErrMissingDimensions                  = errors.New("parcel pricing: dimensions required")
	ErrInvalidFeatureCondition            = errors.New("parcel pricing: invalid feature condition")
	ErrFeatureUnavailable                 = errors.New("parcel pricing: the feature is unavailable for this evaluation")
	ErrInvalidWeightUnit                  = errors.New("parcel pricing: invalid weight unit")
	ErrWeightUnitMismatch                 = errors.New("parcel pricing: weight unit mismatch")
	ErrInvalidIdentifier                  = errors.New("parcel pricing: invalid identifier")
	ErrInvalidDirection                   = errors.New("parcel pricing: invalid pricing direction")
	ErrInvalidPurpose                     = errors.New("parcel pricing: invalid pricing purpose")
	ErrDirectionPurposeMismatch           = errors.New("parcel pricing: pricing purpose does not pair with direction")
	ErrInvalidEvidenceKind                = errors.New("parcel pricing: invalid evidence kind")
	ErrInvalidVersionReference            = errors.New("parcel pricing: invalid version reference")
	ErrDuplicateVersionReference          = errors.New("parcel pricing: duplicate version reference")
	ErrInvalidEffectivePeriod             = errors.New("parcel pricing: invalid effective period")
	ErrPricingPeriodConflict              = errors.New("parcel pricing: pricing period conflict")
	ErrPricingPeriodNotApplicable         = errors.New("parcel pricing: version not applicable at business time")
	ErrInvalidRateEntry                   = errors.New("parcel pricing: invalid rate entry")
	ErrDuplicateRateEntry                 = errors.New("parcel pricing: duplicate rate entry")
	ErrInvalidRateTable                   = errors.New("parcel pricing: invalid rate table")
	ErrRateIntervalOverlap                = errors.New("parcel pricing: rate interval overlap")
	ErrRateTableConflict                  = errors.New("parcel pricing: rate table conflict")
	ErrNoMatchingRate                     = errors.New("parcel pricing: no matching rate")
	ErrInvalidRoundingPolicy              = errors.New("parcel pricing: invalid rounding policy")
	ErrInvalidExclusionRule               = errors.New("parcel pricing: invalid exclusion rule")
	ErrInvalidChargeRule                  = errors.New("parcel pricing: invalid charge rule")
	ErrDuplicateChargeRule                = errors.New("parcel pricing: duplicate charge rule")
	ErrDuplicateChargeRuleOrder           = errors.New("parcel pricing: duplicate charge rule order")
	ErrDuplicateChargeCode                = errors.New("parcel pricing: duplicate charge code")
	ErrInvalidChargeLine                  = errors.New("parcel pricing: invalid charge line")
	ErrInvalidVolumetricFactor            = errors.New("parcel pricing: invalid volumetric factor")
	ErrInvalidSurchargeRule               = errors.New("parcel pricing: invalid surcharge rule")
	ErrDuplicateSurchargeRule             = errors.New("parcel pricing: duplicate surcharge rule")
	ErrUndeclaredExclusivity              = errors.New("parcel pricing: surcharge rule did not declare whether it is exclusive with the others")
	ErrInvalidChargeDependency            = errors.New("parcel pricing: invalid charge dependency")
	ErrInvalidReferenceSeries             = errors.New("parcel pricing: invalid reference series binding")
	ErrMissingReferenceSeriesValue        = errors.New("parcel pricing: bound reference series has no resolved value")
	ErrReferenceSeriesVersionConflict     = errors.New("parcel pricing: resolved reference series reading belongs to a series the plan did not bind")
	ErrInvalidPlanStructures              = errors.New("parcel pricing: invalid pricing plan structures")
	ErrPlanStructuresNotExecutable        = errors.New("parcel pricing: declared plan structures are not executable")
	ErrInvalidPricingPlan                 = errors.New("parcel pricing: invalid pricing plan")
	ErrPricingScopeMismatch               = errors.New("parcel pricing: pricing scope mismatch")
	ErrPricingInputInvalid                = errors.New("parcel pricing: invalid pricing input")
	ErrEvaluationRequestInvalid           = errors.New("parcel pricing: invalid evaluation request")
	ErrInvalidPlanEvaluationTarget        = errors.New("parcel pricing: invalid plan evaluation target")
	ErrEvaluationVersionConflict          = errors.New("parcel pricing: evaluation version conflict")
	ErrEvaluationContentConflict          = errors.New("parcel pricing: evaluation content conflict")
	ErrCanonicalizationVersionUnsupported = errors.New("parcel pricing: canonicalization version not supported by this build")
	ErrReplayEvaluationIDReuse            = errors.New("parcel pricing: replay evaluation ID must be new")
	ErrReplayResultMismatch               = errors.New("parcel pricing: replay result mismatch")
	ErrNegativeChargeTotal                = errors.New("parcel pricing: negative charge total")
	ErrEvaluationArithmetic               = errors.New("parcel pricing: evaluation arithmetic failure")
)
